// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVD1o3yUy-SX1ebpYNAXAagFz3Tc76RCk',
    appId: '1:1011122957384:web:3844d248e90bb984043c7d',
    messagingSenderId: '1011122957384',
    projectId: 'scholar-chat-24',
    authDomain: 'scholar-chat-24.firebaseapp.com',
    storageBucket: 'scholar-chat-24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE28oMfdXO3leekwL_G-R9EMPRvCU5N1Y',
    appId: '1:1011122957384:android:21e5413a62ba54e4043c7d',
    messagingSenderId: '1011122957384',
    projectId: 'scholar-chat-24',
    storageBucket: 'scholar-chat-24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbD4PHDoVkxW1EZRbxGi7pBhS1C69hzws',
    appId: '1:1011122957384:ios:fcce61b1a69404b6043c7d',
    messagingSenderId: '1011122957384',
    projectId: 'scholar-chat-24',
    storageBucket: 'scholar-chat-24.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbD4PHDoVkxW1EZRbxGi7pBhS1C69hzws',
    appId: '1:1011122957384:ios:44548238bb2e63bb043c7d',
    messagingSenderId: '1011122957384',
    projectId: 'scholar-chat-24',
    storageBucket: 'scholar-chat-24.appspot.com',
    iosBundleId: 'com.example.scholarChat.RunnerTests',
  );
}
